# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marker < Formula
  desc "Command-line client for Marker"
  homepage "https://docs.usemarker.ai/docs/cli"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.1/marker_0.3.1_darwin_amd64.tar.gz"
      sha256 "3ca32b5d985de0ea37a2b9b15ff903d0fe64c380325fc609201b9c483ddb1ffd"

      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.1/marker_0.3.1_darwin_arm64.tar.gz"
      sha256 "c4fa1f757b79209fb78f494d1cc40c865044f103ee021b3fdbf24dfb1c5d9f62"

      def install
        bin.install "marker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.1/marker_0.3.1_linux_amd64.tar.gz"
      sha256 "75ca731acf80da88ce968758cf85259d5ccd8a6949234236737ee92e3c86d37f"
      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.1/marker_0.3.1_linux_arm64.tar.gz"
      sha256 "601475dfe19b9ceb16324a135bac759b3db070f3162a1e06ddc4b06878715336"
      def install
        bin.install "marker"
      end
    end
  end

  test do
    system "#{bin}/marker", "--help"
  end
end
