# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marker < Formula
  desc "Command-line client for Marker"
  homepage "https://docs.usemarker.ai/docs/cli"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.0/marker_0.3.0_darwin_amd64.tar.gz"
      sha256 "f429c2f840063dd069a9eb84f4b952086ba30618133ca7f56019d0d3d8c71539"

      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.0/marker_0.3.0_darwin_arm64.tar.gz"
      sha256 "18761260be0de28cf4addbdfc7ae16440434b35d3905e98348b380f69b5a47dd"

      def install
        bin.install "marker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.0/marker_0.3.0_linux_amd64.tar.gz"
      sha256 "951cfd40f913d51d8d8eb82e0ea50f140f34de3449d8468c38dbad45797ebb58"
      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.0/marker_0.3.0_linux_arm64.tar.gz"
      sha256 "75efb0162939741d4343eb8f7144c3ae3f58bb162956dd1b27448d8486a4cbe8"
      def install
        bin.install "marker"
      end
    end
  end

  test do
    system "#{bin}/marker", "--help"
  end
end
