# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Marker < Formula
  desc "Command-line client for Marker"
  homepage "https://docs.usemarker.ai/docs/cli"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.3/marker_0.3.3_darwin_amd64.tar.gz"
      sha256 "fadb6b2d4a6b4239ec6d6d0815d08ea078fd7d702b049764687179444e95db20"

      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.3/marker_0.3.3_darwin_arm64.tar.gz"
      sha256 "e146f10c1b64a82f5cbac973b681ed5fb1a3ad5cda778f42e003360db0856092"

      def install
        bin.install "marker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.3/marker_0.3.3_linux_amd64.tar.gz"
      sha256 "237df9569e6da83ae4f7bc2b243e335c68c8988b3331eab4d4dcf82d7b0e285d"
      def install
        bin.install "marker"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/marker-ai/marker-cli/releases/download/v0.3.3/marker_0.3.3_linux_arm64.tar.gz"
      sha256 "b3bc6e79294a5db6e5911700a986b1ca24b22ec3d1d59f8855953f17a7bd2bd4"
      def install
        bin.install "marker"
      end
    end
  end

  test do
    system "#{bin}/marker", "--help"
  end
end
